// SPDX-License-Identifier: AGPL-3.0-or-later

package core

import (
	"errors"
	"fmt"

	"github.com/google/uuid"
)

// ID is an opaque, canonical UUIDv7 identifier generated by Stackfort.
type ID string

// NewID returns a globally unique, time-ordered identifier using
// cryptographically secure randomness.
func NewID() (ID, error) {
	value, err := uuid.NewV7()
	if err != nil {
		return "", fmt.Errorf("generate UUIDv7: %w", err)
	}
	return ID(value.String()), nil
}

// ParseID accepts only Stackfort's canonical lowercase UUIDv7 representation.
func ParseID(value string) (ID, error) {
	parsed, err := uuid.Parse(value)
	if err != nil || parsed.String() != value || parsed.Version() != uuid.Version(7) {
		return "", errors.New("identifier must be a canonical UUIDv7")
	}
	return ID(value), nil
}

func validateID(value ID, field string) error {
	if _, err := ParseID(string(value)); err != nil {
		return fmt.Errorf("%w: %s: %v", ErrInvalidInput, field, err)
	}
	return nil
}

func validateOptionalID(value *ID, field string) error {
	if value == nil {
		return nil
	}
	return validateID(*value, field)
}

func nullableID(value *ID) any {
	if value == nil {
		return nil
	}
	return string(*value)
}
