// SPDX-License-Identifier: AGPL-3.0-or-later

package storageprep

import (
	"encoding/json"
	"strings"
	"testing"
)

func bootEnvironment(lines string) []byte {
	data := "# GRUB Environment Block\n" + lines
	return []byte(data + strings.Repeat("#", 1024-len(data)))
}

func TestOfflineBootAuthorizationRequiresAllIndependentGates(t *testing.T) {
	plan := testPlan()
	state := State{SchemaVersion: SchemaVersion, Plan: plan, Phase: AwaitingReboot, ArmAttempts: 1}
	observed := newBackend(&memoryStore{}).observation
	observed.BootID = nextBoot
	cmdline := "root=PARTUUID=" + plan.PartitionUUID + " ro stackfort.native-quota=" + plan.OperationID
	env := bootEnvironment("stackfort_native_consumed=" + plan.OperationID + "\n")
	if err := CheckBootAuthorization(state, plan, observed, cmdline, env); err != nil {
		t.Fatal(err)
	}
	for _, phase := range []Phase{Planned, Arming, Verifying, Ready, RecoveryRequired} {
		bad := state
		bad.Phase = phase
		if err := CheckBootAuthorization(bad, plan, observed, cmdline, env); err == nil {
			t.Fatalf("%s authorized offline mutation", phase)
		}
	}
	for _, line := range []string{"", cmdline + " stackfort.native-quota=" + plan.OperationID, strings.Replace(cmdline, plan.OperationID, nextBoot, 1), "notstackfort.native-quota=" + plan.OperationID} {
		if err := CheckBootAuthorization(state, plan, observed, line, env); err == nil {
			t.Fatal("bad kernel token accepted", line)
		}
	}
	for _, lines := range []string{"", "stackfort_native_consumed=" + nextBoot + "\n", "stackfort_native_consumed=" + plan.OperationID + "\nnext_entry=anything\n", "stackfort_native_consumed=" + plan.OperationID + "\nstackfort_native_armed=" + plan.OperationID + "\n"} {
		if err := CheckBootAuthorization(state, plan, observed, cmdline, bootEnvironment(lines)); err == nil {
			t.Fatal("unconsumed boot accepted")
		}
	}
	oldBoot := observed
	oldBoot.BootID = plan.PreviousBootID
	if err := CheckBootAuthorization(state, plan, oldBoot, cmdline, env); err == nil {
		t.Fatal("original boot accepted")
	}
	other := plan
	other.ManifestDigest = strings.Repeat("c", 64)
	if err := CheckBootAuthorization(state, other, observed, cmdline, env); err == nil {
		t.Fatal("different manifest accepted")
	}
	for _, change := range []func(*Observation){func(o *Observation) { o.MachineID = nextBoot }, func(o *Observation) { o.RootUUID = nextBoot }, func(o *Observation) { o.PartitionUUID = nextBoot }, func(o *Observation) { o.Kernel = "6.13" }} {
		bad := observed
		change(&bad)
		if err := CheckBootAuthorization(state, plan, bad, cmdline, env); err == nil {
			t.Fatal("host drift accepted")
		}
	}
}

func TestStrictOfflineJournalAndGRUBDecoder(t *testing.T) {
	if _, err := ParseGRUBEnvironment(bootEnvironment("# WARNING: Do not edit this file by tools other than grub-editenv!!!\nstackfort_native_consumed=one\n")); err != nil {
		t.Fatal(err)
	}
	state := State{SchemaVersion: SchemaVersion, Plan: testPlan(), Phase: AwaitingReboot, ArmAttempts: 1}
	canonical, err := json.MarshalIndent(state, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	canonical = append(canonical, '\n')
	decoded, err := DecodeState(canonical)
	if err != nil || decoded != state {
		t.Fatal(err)
	}
	for _, data := range [][]byte{[]byte("{"), append(append([]byte(nil), canonical...), []byte("{}")...), []byte(strings.Replace(string(canonical), `"phase":`, `"phase": "ready", "phase":`, 1)), []byte(strings.Repeat("x", maximumStateBytes+1))} {
		if _, err := DecodeState(data); err == nil {
			t.Fatal("invalid offline journal accepted")
		}
	}
	for _, data := range [][]byte{nil, []byte("# GRUB Environment Block\n"), bootEnvironment("next_entry=x\nnext_entry=y\n"), bootEnvironment("bad-key=x\n"), bootEnvironment("x=bad\r\n"), bootEnvironment("next_entry\n"), bootEnvironment("#garbage\n")} {
		if _, err := ParseGRUBEnvironment(data); err == nil {
			t.Fatal("unsafe GRUB environment accepted")
		}
	}
}

func TestOneShotEntryPreservesDefaultAndHasSafeConsumedFallback(t *testing.T) {
	plan := testPlan()
	entry, err := RenderGRUBEntry(plan)
	if err != nil {
		t.Fatal(err)
	}
	for _, required := range []string{"save_env stackfort_native_armed stackfort_native_consumed", "stackfort.native-quota=" + plan.OperationID, "initrd /boot/initrd.img-" + plan.Kernel, "initrd /boot/stackfort-native-quota-" + plan.OperationID + ".img", "root=PARTUUID=" + plan.PartitionUUID} {
		if !strings.Contains(entry, required) {
			t.Fatal("missing", required)
		}
	}
	if strings.Contains(entry, "set default=") || strings.Count(entry, "stackfort.native-quota=") != 1 || strings.Index(entry, "save_env") > strings.Index(entry, "  linux") {
		t.Fatal("unsafe one-shot entry ordering")
	}
	plan.Kernel = "6.12; reboot"
	if _, err := RenderGRUBEntry(plan); err == nil {
		t.Fatal("shell/GRUB metacharacters accepted")
	}
}
