// SPDX-License-Identifier: AGPL-3.0-or-later

package storageprep

import (
	"bytes"
	"encoding/json"
	"errors"
	"io"
	"strings"
)

// DecodeState is shared by the descriptor store and the lab's read-only
// offline journal reader. Reading a root journal must never require mounting
// the filesystem which is about to undergo offline checking.
func DecodeState(content []byte) (State, error) {
	if len(content) > maximumStateBytes {
		return State{}, errors.New("storage journal exceeds size limit")
	}
	var state State
	decoder := json.NewDecoder(bytes.NewReader(content))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&state); err != nil {
		return State{}, err
	}
	if decoder.Decode(&struct{}{}) != io.EOF {
		return State{}, errors.New("storage journal contains trailing data")
	}
	if err := state.Validate(); err != nil {
		return State{}, err
	}
	canonical, err := json.MarshalIndent(state, "", "  ")
	if err != nil || !bytes.Equal(content, append(canonical, '\n')) {
		return State{}, errors.New("storage journal is not canonical JSON")
	}
	return state, nil
}

// CheckBootAuthorization is a read-only policy gate. The caller must first
// prove the target is unmounted and independently verify the immutable
// manifest, actual machine/device identity, geometry and executable digest.
// GRUB consumption is evidence, not a power-loss durability guarantee.
func CheckBootAuthorization(state State, plan Plan, observed Observation, commandLine string, environment []byte) error {
	if err := state.Validate(); err != nil {
		return err
	}
	if state.Plan != plan || state.Phase != AwaitingReboot || state.ArmAttempts != 1 ||
		observed.MachineID != plan.MachineID || observed.RootUUID != plan.RootUUID ||
		observed.PartitionUUID != plan.PartitionUUID || observed.Kernel != plan.Kernel ||
		!canonicalUUID(observed.BootID) || observed.BootID == plan.PreviousBootID {
		return errors.New("offline storage journal/host does not authorize this boot")
	}
	count := 0
	for _, token := range strings.Fields(commandLine) {
		if value, ok := strings.CutPrefix(token, "stackfort.native-quota="); ok {
			count++
			if value != plan.OperationID {
				return errors.New("wrong one-shot kernel token")
			}
		}
	}
	if count != 1 {
		return errors.New("missing or duplicate one-shot kernel token")
	}
	env, err := ParseGRUBEnvironment(environment)
	if err != nil {
		return err
	}
	if env["next_entry"] != "" || env["stackfort_native_armed"] != "" || env["stackfort_native_consumed"] != plan.OperationID {
		return errors.New("GRUB did not consume the native preparation entry")
	}
	return nil
}

// ParseGRUBEnvironment accepts only the regular 1024-byte environment block
// used by the qualified Debian lab, not GRUB's other storage backends.
func ParseGRUBEnvironment(content []byte) (map[string]string, error) {
	const header = "# GRUB Environment Block\n"
	if len(content) != 1024 || !bytes.HasPrefix(content, []byte(header)) {
		return nil, errors.New("unsupported GRUB environment block")
	}
	env := make(map[string]string)
	rest := string(content[len(header):])
	// grub-editenv 2.12-9+deb13u2 includes this literal vendor warning.
	rest = strings.TrimPrefix(rest, "# WARNING: Do not edit this file by tools other than grub-editenv!!!\n")
	for len(rest) > 0 && rest[0] != '#' {
		line, tail, ok := strings.Cut(rest, "\n")
		if !ok {
			return nil, errors.New("incomplete GRUB environment")
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok || key == "" {
			return nil, errors.New("invalid GRUB variable")
		}
		for _, char := range key {
			if !(char >= 'a' && char <= 'z' || char >= 'A' && char <= 'Z' || char >= '0' && char <= '9' || char == '_') {
				return nil, errors.New("invalid GRUB key")
			}
		}
		for _, char := range value {
			if char < 32 || char > 126 {
				return nil, errors.New("invalid GRUB value")
			}
		}
		if _, exists := env[key]; exists {
			return nil, errors.New("duplicate GRUB variable")
		}
		env[key], rest = value, tail
	}
	if strings.Trim(rest, "#") != "" {
		return nil, errors.New("invalid GRUB padding")
	}
	return env, nil
}

func GRUBEntryID(plan Plan) (string, error) {
	if err := plan.Validate(); err != nil {
		return "", err
	}
	return "stackfort-native-quota-" + plan.OperationID, nil
}

// RenderGRUBEntry is deliberately limited to the Debian plain-GPT/ext4 lab.
// No existing/default entry is replaced. A consumed entry boots the original
// initrd without the preparation token, even if selected again manually.
func RenderGRUBEntry(plan Plan) (string, error) {
	id, err := GRUBEntryID(plan)
	if err != nil {
		return "", err
	}
	linux := "  linux /boot/vmlinuz-" + plan.Kernel + " root=PARTUUID=" + plan.PartitionUUID + " ro console=tty0 console=ttyS0,115200 consoleblank=0"
	return "menuentry 'Stackfort native quota preparation (lab)' --id '" + id + "' {\n" +
		"  insmod part_gpt\n  insmod ext2\n  search --no-floppy --fs-uuid --set=root " + plan.RootUUID + "\n" +
		"  if [ \"$stackfort_native_armed\" = \"" + plan.OperationID + "\" ]; then\n" +
		"    set stackfort_native_armed=\n    set stackfort_native_consumed=" + plan.OperationID + "\n" +
		"    save_env stackfort_native_armed stackfort_native_consumed\n" +
		linux + " stackfort.native-quota=" + plan.OperationID + "\n" +
		"    initrd /boot/" + id + ".img\n  else\n" + linux + "\n" +
		"    initrd /boot/initrd.img-" + plan.Kernel + "\n  fi\n}\n", nil
}
